### ISSUE TITLE
[FEATURE] Default exclude "build" and "dist" are partial matches

### ISSUE THREAD

**Issue by jayvdb** [djlint/djLint#102]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

This is a bit like a bug, at least for me, as `build` in the default exclude list matches a rather large app in my project : `builder`.  So it was completely ignored until now, and I only noticed because I was investigating https://github.com/Riverside-Healthcare/djLint/issues/101 .

I guess the same can easily happen with `dist`, while the rest of the entries in `default_exclude` look unlikely to accidentially match real files.

The easiest solution would be for `default_exclude` to only match complete dir-names - no partial matches.
And it would be great if, at the end of djlint results, print how many files were filtered out by `get_src` and from which paths. e.g. "X *.html results ignored from .tox and .venv"

But IMO a better approach would be to construct the `default_exclude` from `.*ignore` files, e.g. `.gitignore`, if any are present in cwd or parents.  There are a few parsers [on pypi](https://www.google.com/search?q=gitignore+site%3Apypi.org).

**Comment by christopherpickering** [comment]
Maybe call it something along the lines of "use_git_ignore"? Or something more inclusive?
