### ISSUE TITLE
[FEATURE] Compatibility with djade

### ISSUE THREAD

**Issue by rphlo** [djlint/djLint#1021]
- [x] I've searched the [issues](https://github.com/djlint/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request
Hi, First thanks for this project,
Here is my request.

Recently a new project was released https://github.com/adamchainz/djade and it has conflicting formatting rules regarding django jinja templates.
Biggest conflict is regarding white lines around `{% block %}`, smaller conflict is about naming inlines `{% endblock %}`

Would be nice to see a common approach regarding those.

I posted a feature request as well in djade repo.
https://github.com/adamchainz/djade/issues/101

**Comment by monosans** [comment]
What is the point of this? What will it give to djLint and djade users?

**Comment by monosans** [comment]
Why would anyone use 2 formatters for the same file type

**Comment by oliverhaas** [comment]
Why not use djlint for everything? If you want "compatibility", you actually would need to implement the proper formatting in djlint, basically making using djade superfluous.

Can you give an actual example for formatting conflicts?
