### ISSUE TITLE
[BUG] H025 Tag seems to be an orphan. <!-- /.modal -->

### ISSUE THREAD

**Issue by jayvdb** [djlint/djLint#70]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3.7
 - djLint Version: 0.5.4

## Issue
I am seeing `H025 Tag seems to be an orphan.` for HTML comments like `<!-- /.modal -->`

**Comment by christopherpickering** [comment]
Thanks - on the link tag, is it self closing, or missing the "/>"?

**Comment by christopherpickering** [comment]
I see the issue.. I'm going to update that regex as well to include tags that have template syntax.
