### ISSUE TITLE
[BUG] H020 Empty tag pair found. Consider removing. <td></td>

### ISSUE THREAD

**Issue by jayvdb** [djlint/djLint#74]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3.7
 - djLint Version: 0.5.4

## Issue
TD & TH are valid even if empty.

**Comment by christopherpickering** [comment]
Do you have a link to a list of what tags can be empty vs not empty?
