### ISSUE TITLE
[BUG] [Linter] `.djlintrc` not loading since 1.34.0

### ISSUE THREAD

**Issue by yndajas** [djlint/djLint#767]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: macOS Ventura 13.5.2
 - Python Version: 3.11.5 (`python3`)
 - djLint Version: 1.34.0
 - template language: Nunjucks

## Issue

After upgrading from 1.33.0 to 1.34.0, I now see this when running djLint:

```
Failed to load .djlintrc file. cannot access local variable 'content' where it is not associated with a value
```

It still lints, but I guess it's not loading config properly. I haven't looked at this commit in detail, but I guess it's related (since it changed config loading and was included in 1.34.0): https://github.com/Riverside-Healthcare/djLint/commit/d8a059ac32027c956fbae762ce6de44f5d47826c

## How To Reproduce

I'm not too sure about a generic way to reproduce this, but the project I'm running it on is [ministryofjustice/hmpps-accredited-programmes-ui](https://github.com/ministryofjustice/hmpps-accredited-programmes-ui). You could clone that, run `script/setup` and then `djlint .` or `npm run lint`

When running djLint, it will output the error mentioned above

## Contents of .djlintrc/pyproject.toml [tool.djlint]

```json
{
  "extension": "njk",
  "profile": "nunjucks"
}
```

**Comment by aslak01** [comment]
+1 on having this problem.

**Comment by simplegr** [comment]
here also!

**Comment by christopherpickering** [comment]
Thanks, I think someone has a pr that will fix this one. I should get it release shortly, sorry for the long out of office.
