### ISSUE TITLE
[BUG] [Linter] djLint is trying to lint .py files

### ISSUE THREAD

**Issue by ahmedsaoudi** [djlint/djLint#782]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: ubuntu 20.04
 - Python: 3.8.10
 - djLint: 1.34.0
 - djLint VSCode: v2023.8.10
 - template language: django-html

## Issue
The linter is displaying `Found extra blank lines. (H014)` in Python files. According to the documentation, the `H` in the error code refers to an HTML error, which is not the case here.

## How To Reproduce
- open vscode with djlint installed and activated;
- open a .py file where a line of code is followed by 2 empty lines;
- the line of code is underlined with red. When said line is hover, the message `Found extra blank lines. (H014)` appeards; 
- the output tab is spammed with multiple occurences of this error (number depending on file length). 

## Contents of VSCode settings.json
```
    "djlint.formatLanguages": [
        "django-html",
        "jinja",
        "jinja-html",
        "nj",
        "njk",
        "nunjucks",
        "twig",
        "handlebars",
        "hbs",
        "mustache",
        "html"
    ],
```

**Comment by christopherpickering** [comment]
Do you have a djlint config somewhere?

**Comment by ahmedsaoudi** [comment]
@christopherpickering the snippet above is all the config I have for djlint.

**Comment by christopherpickering** [comment]
Hmm, it must be something vscode related? Have you tried opening an issue at https://github.com/monosans/djlint-vscode? @monosans may have more ideas.

**Comment by monosans** [comment]
I assume you have the VSCode `djlint.enableLinting` setting globally enabled, whereas it should be enabled for each language separately.

**Comment by ahmedsaoudi** [comment]
That was it! I moved to setting and [html][django-html] and it works as intended. Thanks @christopherpickering and @monosans! 

One last question, if I may: is the `djlint.formatLanguages` still necessary now that I move the `enableLinting` setting under the targeted languages? Is this redundant or they each have a different purpose?

**Comment by monosans** [comment]
> is the `djlint.formatLanguages` still necessary now that I move the `enableLinting` setting under the targeted languages? Is this redundant or do they each serve a different purpose?

They have different purposes. `enableLinting` determines which languages will be linted, and `formatLanguages` determines which languages will be formatted.

**Comment by ahmedsaoudi** [comment]
@monosans thanks a lot!

**Comment by ahmedsaoudi** [comment]
@monosans thanks a lot!
