### ISSUE TITLE
[BUG] [Linter] New version vscode extension breaks formatting/linting

### ISSUE THREAD

**Issue by BrianLYS** [djlint/djLint#833]
## System Info
 - OS: MACOS
 - Python Version (3.10.11, 3.11.8)
 - djLint Version (v2024.5.0)
 - template language: jinja

## Issue
Updating to latest djlint version breaks linter and formatter. 

## How To reproduce
Upgrade to v2024.5.0

## How to fix
Reverting back to v2023.11.0

## Contents of .djlintrc/pyproject.toml [tool.djlint]
```
[tool.ruff.lint]
select = ["ALL"]

[tool.ruff]
line-length = 120
select = ["F"]

[tool.djlint]
profile="jinja"
```

**Comment by monosans** [comment]
Hi. I have everything working on Windows. Are any errors displayed?

The only difference between the two versions is the updated version of [execa](https://github.com/sindresorhus/execa), maybe that's the problem.

And please, the next time you have a problem with a VSCode extension, create an issue in the appropriate repository.

**Comment by monosans** [comment]
Subsequent discussions will take place [here](https://github.com/djlint/djlint-vscode/issues/741).
