### ISSUE TITLE
[BUG] [Formatter] pip install cssbeautifier is failing on the new setuptools

### ISSUE THREAD

**Issue by cclauss** [djlint/djLint#877]
* beautifier/js-beautify#2300
* beautifier/js-beautify#2301

**Comment by agusmakmun** [comment]
This being popular here: https://github.com/pypa/setuptools/issues/4519

**Comment by MatthewEthanTam** [comment]
bump, any updates on this issue?

**Comment by cclauss** [comment]
This was fixed in setuptool so everything should work again.
